apiVersion: apps/v1
kind: Deployment

metadata:
  name: swiftroute-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: swiftroute-backend

  template:
    metadata:
      labels:
        app: swiftroute-backend

    spec:
      containers:
        - name: swiftroute-backend
          image: swiftroute-backend:latest
          ports:
            - containerPort: 8080