name: SwiftRoute CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: swiftroute
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d swiftroute"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_URL: jdbc:postgresql://localhost:5432/swiftroute
      DB_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build and test
        run: bash mvnw clean test

      - name: Validate Kubernetes manifest
        uses: azure/k8s-lint@v4
        with:
          manifests: |
            k8s/deployment.yaml
          kubeconformOpts: -summary